### DISCUSSION TITLE
Help using Ansible

### DISCUSSION THREAD

**Discussion by clebsonwendler** [iamgini/ansible-real-life#3] [General]
I don't know if it would be an idea to create this forum, but with your experience I believe it can help many people who are having some difficulties with ansible.

I'm creating some EC2 instances on AWS, I found your repository and it helped me a lot. I'm just not able to retrieve the "public_ip" variable so that I can automate the insertion of IPs in the inventory file.

Do you have any tips for this? For example:

```
- name : Add instance to host group
        add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
        loop: "{{ created_ec2.instances }}"
```

It informs you that the **public_ip** variable has not been set. In older versions of ansible this worked.

**Comment by iamgini** [comment]
Hi @clebsonwendler 
Glad to hear it helped. But can I see the task for ec2 creation?
Please check the `wait` and `wait_timeout` arguments are set properly. If the task is not waiting for the ec2 creation to be completed, then you will not get public IP. 

Please test and let me know.

**Reply by clebsonwendler** [reply]
It was like this:

```
- name: Create Security Groups
  local_action:
    module: ec2_group
    name: "{{ security_group }}"
    description: Ansible lab
    region: "{{ region }}"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
  register: basic_firewall

- name: Create EC2
  local_action:
    module: ec2_instance
    profile: default
    key_name: "{{ keypair }}"
    security_group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image }}"
    state: present
    wait: yes
    wait_timeout: 300
    #count: "{{ count }}"
    region: "{{ region }}"
    tags:
      Name: "{{ item.value.name }}"
    detailed_monitoring: no
    network:
      assign_public_ip: yes
  loop: "{{ lookup('dict', ec2_new_list, wantlist=True) }}"
  register: created_ec2
```
